# Generated by Django 4.2.6 on 2023-10-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='answer',
            field=models.CharField(blank=True, choices=[('Sí asistiré', 'Sí asistiré'), ('No asistiré', 'No, asistiré')], default='Sí asistiré', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='guests_names',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='num_guests_selected',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
