# Generated by Django 4.2.6 on 2023-10-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_alter_guests_answer_alter_guests_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='answer',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Sí asistiré', 'Sí asistiré'), ('No asistiré', 'No, asistiré')], default='Sí asistiré', max_length=100, null=True),
        ),
    ]
