# Generated by Django 4.2.6 on 2023-10-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_alter_guests_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='answer',
            field=models.CharField(blank=True, choices=[('Sí asistiré', 'Sí asistiré'), ('No asistiré', 'No asistiré')], default='Pendiente', max_length=100, null=True),
        ),
    ]
