# Generated by Django 4.2.6 on 2024-01-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0005_alter_guests_guests_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='num_guests_selected_char',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
