# Generated by Django 4.2.6 on 2024-01-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0006_guests_num_guests_selected_char'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='num_guests_selected_char',
        ),
        migrations.AlterField(
            model_name='guests',
            name='num_guests_selected',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
